# Generated by Django 5.1.5 on 2025-01-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_fuelstation_latitude_fuelstation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
